# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import firedetection_pb2 as firedetection__pb2


class FireDetectionGRPCStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TakeAlarm = channel.unary_unary(
                '/firedetection.FireDetectionGRPC/TakeAlarm',
                request_serializer=firedetection__pb2.GetRequest.SerializeToString,
                response_deserializer=firedetection__pb2.ReturnResponse.FromString,
                )


class FireDetectionGRPCServicer(object):
    """The greeting service definition.
    """

    def TakeAlarm(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FireDetectionGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TakeAlarm': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeAlarm,
                    request_deserializer=firedetection__pb2.GetRequest.FromString,
                    response_serializer=firedetection__pb2.ReturnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'firedetection.FireDetectionGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FireDetectionGRPC(object):
    """The greeting service definition.
    """

    @staticmethod
    def TakeAlarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firedetection.FireDetectionGRPC/TakeAlarm',
            firedetection__pb2.GetRequest.SerializeToString,
            firedetection__pb2.ReturnResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
