# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firedetection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66iredetection.proto\x12\rfiredetection\"A\n\nGetRequest\x12\x10\n\x08\x63\x61meraID\x18\x01 \x01(\t\x12\x13\n\x0bpercentFire\x18\x02 \x01(\t\x12\x0c\n\x04Time\x18\x03 \x01(\t\"!\n\x0eReturnResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x11\x46ireDetectionGRPC\x12\x45\n\tTakeAlarm\x12\x19.firedetection.GetRequest\x1a\x1d.firedetection.ReturnResponseB\x1c\xaa\x02\x19\x46ireDetection.Grpc.Systemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firedetection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\031FireDetection.Grpc.System'
  _globals['_GETREQUEST']._serialized_start=38
  _globals['_GETREQUEST']._serialized_end=103
  _globals['_RETURNRESPONSE']._serialized_start=105
  _globals['_RETURNRESPONSE']._serialized_end=138
  _globals['_FIREDETECTIONGRPC']._serialized_start=140
  _globals['_FIREDETECTIONGRPC']._serialized_end=230
# @@protoc_insertion_point(module_scope)
