Quang Trang Minh
version: '3.4'
networks:
  web:
    external: true

services:
  firedetection.backend.api:
    image: ${DOCKER_REGISTRY-}firedetectionbackendapi
    build:
      context: .
      dockerfile: FireDetection.Backend.API/Dockerfile
    container_name: firedetection.api
    ports:
      - "4211:80"
    tty: true
    environment: 
       -  ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=firedetection.database;Port=5432;Database=FireDetectionDatabase;Include Error Detail=true;Integrated Security=true;Pooling=true
    depends_on:
        -  "firedetection.database"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  
  firedetection.database:
    image: postgres:latest
    container_name: firedetection.database
    environment:
       POSTGRES_DB: FireDetectionDatabase
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - app_data:/var/lib/postgresql/data


volumes:
  app_data: {}
